# Generated by Django 5.2.10 on 2026-01-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(editable=False, help_text='Six-digit filename (e.g., 000001)', max_length=6, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Configuration name (from metadata.name)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Configuration description')),
                ('author', models.CharField(blank=True, help_text='Configuration author', max_length=200)),
                ('config_data', models.JSONField(help_text='Complete configuration as JSON')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Configuration',
                'verbose_name_plural': 'Chatbot Configurations',
                'ordering': ['name'],
            },
        ),
    ]
