# Generated by Django 5.2.10 on 2026-01-11 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this datasource', max_length=200)),
                ('portal_datasource_id', models.CharField(help_text="Portal's internal datasource identifier", max_length=200)),
                ('description', models.TextField(help_text='What data this datasource provides')),
                ('primary_entity', models.CharField(help_text='The main entity type (e.g., Opportunity, Account)', max_length=100)),
                ('refresh_frequency', models.CharField(default='daily', help_text='How often the underlying data refreshes', max_length=50)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='configs.configurationfile')),
            ],
            options={
                'verbose_name': 'Datasource',
                'verbose_name_plural': 'Datasources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Business term (e.g., ARR, MRR)', max_length=100)),
                ('definition', models.TextField(help_text='Definition of the term')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_terms', to='configs.configurationfile')),
            ],
            options={
                'verbose_name': 'Business Term',
                'verbose_name_plural': 'Business Terms',
                'ordering': ['term'],
                'unique_together': {('configuration', 'term')},
            },
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Technical field name (e.g., 'amount', 'stage')", max_length=100)),
                ('business_name', models.CharField(help_text='User-friendly name for this field', max_length=200)),
                ('description', models.TextField(help_text='What this field represents')),
                ('format', models.CharField(default='text', help_text='Data format: currency, text, date, number, percentage, etc.', max_length=50)),
                ('valid_values', models.TextField(blank=True, help_text='Comma-separated list of valid values (if applicable)')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='configs.configurationfile')),
            ],
            options={
                'verbose_name': 'Field Mapping',
                'verbose_name_plural': 'Field Mappings',
                'ordering': ['field_name'],
                'unique_together': {('configuration', 'field_name')},
            },
        ),
    ]
