# Generated by Django 5.2.10 on 2026-01-12 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_datasource_businessterm_fieldmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedrockCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_access_key_id', models.CharField(help_text='AWS Access Key ID', max_length=200)),
                ('aws_secret_access_key', models.CharField(help_text='AWS Secret Access Key', max_length=200)),
                ('aws_region', models.CharField(default='us-east-1', help_text='AWS Region', max_length=50)),
            ],
            options={
                'verbose_name': 'Bedrock Credentials',
                'verbose_name_plural': 'Bedrock Credentials',
            },
        ),
        migrations.CreateModel(
            name='OpenAICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='OpenAI API Key', max_length=200)),
                ('organization_id', models.CharField(blank=True, help_text='OpenAI Organization ID (optional)', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'OpenAI Credentials',
                'verbose_name_plural': 'OpenAI Credentials',
            },
        ),
        migrations.AddField(
            model_name='configurationfile',
            name='file_format',
            field=models.CharField(choices=[('json', 'JSON'), ('yaml', 'YAML')], default='json', help_text='File format (JSON or YAML)', max_length=4),
        ),
        migrations.CreateModel(
            name='LLMCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('anthropic_bedrock', 'Anthropic Bedrock'), ('openai', 'OpenAI')], help_text='LLM Provider', max_length=20)),
                ('anthropic_bedrock', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_credentials', to='configs.bedrockcredentials')),
                ('openai', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_credentials', to='configs.openaicredentials')),
            ],
            options={
                'verbose_name': 'LLM Credentials',
                'verbose_name_plural': 'LLM Credentials',
            },
        ),
        migrations.AddField(
            model_name='configurationfile',
            name='llm_credentials',
            field=models.OneToOneField(blank=True, help_text='LLM provider credentials', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='configs.llmcredentials'),
        ),
    ]
